### ISSUE TITLE
How to disable right mouse click menu on toolbar

### ISSUE THREAD

**Issue by smopro** [slorelee/pexplorer#2]
I need disable this menu because i will use another application to settings - how i can disable rmb click menu? WinxShell version 4.6

**Comment by slorelee** [comment]
You can find the MENU resource in rc file.

D:\dev\WinXShell\explorer-en.rc(68):IDM_DESKTOPBAR MENU

and the action when you right clicked the toolbar.

D:\dev\WinXShell\taskbar\desktopbar.cpp(521):

```cpp
    case WM_CONTEXTMENU: {
        POINTS p;
        p.x = LOWORD(lparam);
        p.y = HIWORD(lparam);
        PopupMenu menu(IDM_DESKTOPBAR);
        SetMenuDefaultItem(menu, 0, MF_BYPOSITION);
        PopupMenu menu(IDM_DESKTOPBAR);
```

you can add an option for enable/disable the menu with JCFG2_DEF macro.

```diff
    case WM_CONTEXTMENU: {
+		if (JCFG2_DEF("JS_TASKBAR", "contextmenu_enabled", true).ToBool()) {
                    ...
                    ...
+                }
                break;
    }
```

**Comment by smopro** [comment]
this sources actual for 4.6 version? or from sources i can build "4.5" version? in compiled version from forum work successfully, thank you
